export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_QTY_CHANGE = 'PRODUCT_QTY_CHANGE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const CART_CLEAN = 'CART_CLEAN';

export const PRODUCT_TO_CART = 'PRODUCT_TO_CART';