export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_CART_PRODUCTS_LIST_REQUEST = 'PRODUCT_CART_PRODUCTS_LIST_REQUEST';
export const PRODUCT_CART_PRODUCTS_LIST_SUCCESS = 'PRODUCT_CART_PRODUCTS_LIST_SUCCESS';
export const PRODUCT_CART_PRODUCTS_LIST_FAIL = 'PRODUCT_CART_PRODUCTS_LIST_FAIL';
export const PRODUCT_CART_PRODUCTS_LIST_QTY_CHANGE = 'PRODUCT_CART_PRODUCTS_LIST_QTY_CHANGE';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETION_REQUEST = 'PRODUCT_DELETION_REQUEST';
export const PRODUCT_DELETION_SUCCESS = 'PRODUCT_DELETION_SUCCESS';
export const PRODUCT_DELETION_FAIL = 'PRODUCT_DELETION_FAIL';

export const PRODUCT_CREATION_REQUEST = 'PRODUCT_CREATION_SAVE_REQUEST';
export const PRODUCT_CREATION_SUCCESS = 'PRODUCT_CREATION_SUCCESS';
export const PRODUCT_CREATION_FAIL = 'PRODUCT_CREATION_FAIL';
export const PRODUCT_CREATION_CLEAN_ERROR = 'PRODUCT_CREATION_CLEAN_ERROR';

export const PRODUCT_QTY_CHANGE = 'PRODUCT_QTY_CHANGE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const CART_CLEAN = 'CART_CLEAN';

export const PRODUCT_TO_CART_UPDATE_AFTER_SIGN_IN = 'PRODUCT_TO_CART_UPDATE_AFTER_SIGN_IN';
export const PRODUCT_TO_CART = 'PRODUCT_TO_CART';

// Sort
export const PRODUCTS_SORT_DATE_DESC = 'PRODUCTS_SORT_DATE_DESC';
export const PRODUCTS_SORT_DATE_ASC = 'PRODUCTS_SORT_DATE_ASC';
export const PRODUCTS_SORT_RATING_DESC = 'PRODUCTS_SORT_RATING_DESC';
export const PRODUCTS_SORT_RATING_ASC = 'PRODUCTS_SORT_RATING_ASC';