export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_UPDATE_CART = 'USER_SIGN_IN_UPDATE_CART';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAIL = 'USER_SIGN_IN_FAIL';
export const USER_SIGN_IN_AFTER_REG = 'USER_SIGN_IN_AFTER_REG';
export const USER_SIGN_IN_AFTER_UPDATE_INFO = 'USER_SIGN_IN_AFTER_UPDATE_INFO';
export const USER_SIGN_IN_AFTER_UPDATE_CART = 'USER_SIGN_IN_AFTER_UPDATE_CART';
export const USER_SIGN_IN_AFTER_UPDATE_AVATAR = 'USER_SIGN_IN_AFTER_UPDATE_AVATAR';
export const USER_SIGN_IN_OUT = 'USER_SIGN_IN_OUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_UPDATE_INFO_REQUEST = 'USER_UPDATE_INFO_REQUEST';
export const USER_UPDATE_INFO_SUCCESS = 'USER_UPDATE_INFO_SUCCESS';
export const USER_UPDATE_INFO_FAIL = 'USER_UPDATE_INFO_FAIL';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_CLEAN_STATE = 'USER_UPDATE_PASSWORD_CLEAN_STATE';

export const USER_UPDATE_AVATAR_REQUEST = 'USER_UPDATE_AVATAR_REQUEST';
export const USER_UPDATE_AVATAR_SUCCESS = 'USER_UPDATE_AVATAR_SUCCESS';
export const USER_UPDATE_AVATAR_FAIL = 'USER_UPDATE_AVATAR_FAIL';